name: publish sdk release to npmjs

on:
  push:
    tags:
      - ams-v**

jobs:
  publish-npmjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
           # Setup .npmrc file to publish to npm
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Get the version
        id: get_version
        run: echo "VERSION=$(echo ${GITHUB_REF##*/} | cut -d v -f 2)" >> $GITHUB_OUTPUT
      - run: npm install
      - run: npm test
      - run: npm run compile
      - run: npm version ${{steps.get_version.outputs.VERSION}} --no-git-tag-version
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

